---
development:
  api_url: http://localhost:3000/api/v0.1
test:
  api_url: http://localhost:3000/api/v0.1
  APP_URL: http://localhost:9292
production:
  api_url: https://winnerwinnerchikendinner.herokuapp.com/api/v0.1
